"use client";

import { useEffect, useState } from "react";
import { buildExperiment, buildGrowthIdeas } from "@/lib/api";
import { Span } from "@/lib/types";
import { Locale, UI_TEXT } from "@/lib/i18n";

interface Props {
  span: Span;
  locale: Locale;
  paperTitle: string;
  sourceText: string;
  onClose: () => void;
}

const STARTER_CODE = `"""
Experiment: Evidence-Linked Reranking mini-test
Generated by PaperLens Lab
"""
import numpy as np
from dataclasses import dataclass


@dataclass
class Passage:
    text: str
    relevance_score: float = 0.0
    evidence_score: float = 0.0


def factual_alignment(query_emb, passage_emb):
    """Cosine similarity between query and passage claim embeddings."""
    return np.dot(query_emb, passage_emb) / (
        np.linalg.norm(query_emb) * np.linalg.norm(passage_emb) + 1e-8
    )


def evidence_linked_rerank(query, passages, alpha=0.4, beta=0.4, gamma=0.2):
    """
    Simplified ELR scoring.
    TODO: Replace with actual NLI classifier for evidential support.
    """
    scored = []
    for p in passages:
        fa = p.relevance_score  # placeholder for factual alignment
        es = 0.5  # TODO: NLI-based evidential support
        cc = 0.5  # TODO: contextual coherence
        elr_score = alpha * fa + beta * es + gamma * cc
        scored.append((elr_score, p))
    return sorted(scored, key=lambda x: -x[0])


# --- Toy experiment ---
if __name__ == "__main__":
    passages = [
        Passage("RAG improves QA accuracy by retrieving relevant docs.", relevance_score=0.9),
        Passage("The weather today is sunny and warm.", relevance_score=0.1),
        Passage("Evidence-based retrieval filters noise.", relevance_score=0.7),
        Passage("Python is a popular programming language.", relevance_score=0.2),
        Passage("Reranking with NLI improves precision.", relevance_score=0.85),
    ]

    results = evidence_linked_rerank("How does reranking improve RAG?", passages)

    print("=== ELR Reranking Results ===")
    for rank, (score, p) in enumerate(results, 1):
        print(f"  #{rank} (score={score:.3f}): {p.text}")

    # Expected: relevant passages ranked higher
    # Failure condition: irrelevant passages in top-3
    top3_scores = [s for s, _ in results[:3]]
    assert all(s > 0.4 for s in top3_scores), "FAIL: irrelevant passage in top-3"
    print("\\nSMOKE TEST PASSED")
`;

export default function LabModal({ span, locale, paperTitle, sourceText, onClose }: Props) {
  const text = UI_TEXT[locale].lab;
  const [backendCard, setBackendCard] = useState("");
  const [starterCode, setStarterCode] = useState(STARTER_CODE);
  const [growthIdeas, setGrowthIdeas] = useState<string[]>([]);
  const [growthStatus, setGrowthStatus] = useState(
    locale === "ko" ? "다음 실험 아이디어 대기 중..." : "Waiting for next ideas...",
  );
  const [backendStatus, setBackendStatus] = useState(
    locale === "ko" ? "백엔드 실험 카드 생성 중..." : "Generating backend experiment card...",
  );

  useEffect(() => {
    let cancelled = false;
    setBackendStatus(locale === "ko" ? "백엔드 실험 카드 생성 중..." : "Generating backend experiment card...");
    setGrowthIdeas([]);
    setGrowthStatus(locale === "ko" ? "다음 실험 아이디어 대기 중..." : "Waiting for next ideas...");
    buildExperiment({ span, paperTitle, sourceText, locale })
      .then(async (result) => {
        if (cancelled) return;
        setBackendCard(result.card);
        setStarterCode(result.starter);
        setBackendStatus(locale === "ko" ? "Python backend 생성 완료" : "Generated by Python backend");
        setGrowthStatus(locale === "ko" ? "Research Growth 아이디어 생성 중..." : "Generating Research Growth ideas...");
        try {
          const growth = await buildGrowthIdeas({
            span,
            paperTitle,
            paperMemory: [
              {
                id: span.id,
                summary: span.original,
                translation: span.translated,
              },
            ],
            miniLabResult: result.card,
            locale,
          });
          if (cancelled) return;
          setGrowthIdeas(growth.ideas.map((idea) => idea.idea));
          if (growth.error || growth.ideas.length === 0) {
            setGrowthStatus(locale === "ko" ? "Growth fallback 확인 필요" : "Growth fallback needs review");
          } else {
            setGrowthStatus(
              growth.usedFallback
                ? `Growth ready (fallback, ${growth.fineTuningSignal})`
                : `Growth ready (${growth.fineTuningSignal})`,
            );
          }
        } catch {
          if (cancelled) return;
          setGrowthStatus(locale === "ko" ? "Growth 생성 실패" : "Growth unavailable");
        }
      })
      .catch(() => {
        if (cancelled) return;
        setBackendStatus(locale === "ko" ? "오프라인 예시 사용 중" : "Using offline example");
      });
    return () => {
      cancelled = true;
    };
  }, [span, paperTitle, sourceText, locale]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="animate-slide-up flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-border bg-surface shadow-xl">
        {/* Header */}
        <div className="flex shrink-0 items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-2">
            <div className="rounded-lg bg-primary-100 p-1.5">
              <svg
                className="text-primary-700"
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h2 className="text-base font-semibold">Lab Mode</h2>
              <p className="text-xs text-text-muted">
                {text.subtitle}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-text-muted transition-colors hover:bg-surface-hover hover:text-text-primary"
          >
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {/* Selected Span */}
          <div className="mb-5 rounded-xl border border-border bg-surface-secondary p-4">
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-text-muted">
              {text.selectedSource}
            </p>
            <p className="mb-2 text-sm text-text-primary">{span.original}</p>
            <p className="text-sm text-text-secondary">{span.translated}</p>
          </div>

          {/* Experiment Spec */}
          <div className="mb-5 grid grid-cols-1 gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-primary-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.paperSays}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {text.paperSaysValue}
              </p>
            </div>

            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-blue-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.interpretation}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {text.interpretationValue}
              </p>
            </div>

            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-orange-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.unsupportedAssumption}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {text.unsupportedAssumptionValue}
              </p>
            </div>
          </div>

          {/* Experiment Design */}
          <div className="mb-5 rounded-xl border border-primary-200 bg-primary-50/50 p-4">
            <p className="mb-3 flex items-center justify-between text-xs font-semibold text-primary-700">
              <span>ExperimentSpec</span>
              <span className="rounded-full bg-surface px-2 py-0.5 text-[10px] text-text-secondary">
                {backendStatus}
              </span>
            </p>
            {backendCard ? (
              <pre className="max-h-64 whitespace-pre-wrap rounded-lg bg-surface p-3 text-xs leading-relaxed text-text-primary">
                {backendCard}
              </pre>
            ) : (
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.hypothesis}
                  </p>
                  <p className="text-text-primary">
                    Reranking with evidence scores improves top-5 precision over
                    relevance-only baseline
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.baseline}
                  </p>
                  <p className="text-text-primary">
                    BM25 + cosine similarity reranking (no NLI)
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.metric}
                  </p>
                  <p className="text-text-primary">
                    Top-5 precision, recall@20, irrelevant ratio in top-k
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.failureCondition}
                  </p>
                  <p className="text-text-primary">
                    Top-5 precision does not improve, or recall drops by
                    &gt;5%
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.ablation}
                  </p>
                  <p className="text-text-primary">
                    Remove evidential support component; use only factual
                    alignment
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.toyDataset}
                  </p>
                  <p className="text-text-primary">
                    50 queries, 500 passages (50% relevant, 50% distractor)
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Research Growth */}
          <div className="mb-5 rounded-xl border border-border bg-surface p-4">
            <p className="mb-3 flex items-center justify-between text-xs font-semibold text-text-primary">
              <span>Research Growth</span>
              <span className="rounded-full bg-surface-secondary px-2 py-0.5 text-[10px] text-text-secondary">
                {growthStatus}
              </span>
            </p>
            {growthIdeas.length > 0 ? (
              <ul className="space-y-2 text-sm text-text-primary">
                {growthIdeas.map((idea, index) => (
                  <li key={`${idea}-${index}`} className="rounded-lg bg-surface-secondary p-3">
                    {idea}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-text-muted">
                {locale === "ko"
                  ? "실험 카드와 선택한 원문을 바탕으로 다음에 테스트할 아이디어를 준비합니다."
                  : "PaperLens will use the selected span and mini-lab result to suggest the next testable ideas."}
              </p>
            )}
          </div>

          {/* Starter Code */}
          <div className="rounded-xl border border-border">
            <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-text-primary">
                  starter.py
                </span>
                <span className="rounded bg-yellow-100 px-1.5 py-0.5 text-[10px] font-medium text-yellow-700">
                  {text.todos}
                </span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] font-medium text-green-700">
                  {text.smokeTestIncluded}
                </span>
                <button className="rounded-md border border-border px-2.5 py-1 text-[11px] font-medium text-text-secondary hover:bg-surface-hover">
                  {text.copy}
                </button>
              </div>
            </div>
            <pre className="max-h-64 overflow-auto bg-slate-950 p-4 text-xs leading-relaxed text-slate-200">
              <code>{starterCode}</code>
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="flex shrink-0 items-center justify-between border-t border-border px-6 py-3">
          <p className="text-[11px] text-text-muted">
            {text.reviewWarning}
          </p>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="rounded-lg border border-border px-4 py-2 text-xs font-medium text-text-secondary hover:bg-surface-hover"
            >
              {text.close}
            </button>
            <button className="rounded-lg bg-primary-600 px-4 py-2 text-xs font-semibold text-white hover:bg-primary-700">
              {text.download}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
