"use client";

import { useEffect, useState } from "react";
import { buildExperiment, buildGrowthIdeas, MiniLabRunResult, runMiniLab, runStarterCode } from "@/lib/api";
import { Span } from "@/lib/types";
import { Locale, UI_TEXT } from "@/lib/i18n";

interface Props {
  span: Span;
  locale: Locale;
  paperId: string;
  paperTitle: string;
  sourceText: string;
  onClose: () => void;
}

const STARTER_CODE = `"""
Starter mini-lab generated from a selected paper span.
Dependency-free smoke test. Replace EXAMPLES with paper-specific rows.
"""


def baseline(example: str) -> dict:
    return {
        "prediction": example,
        "notes": "Direct baseline without the selected paper mechanism.",
    }


def paper_inspired(example: str) -> dict:
    return {
        "prediction": example,
        "notes": "Minimal paper-inspired variant named by the selected span.",
    }


def score(output: dict, expected: str) -> float:
    prediction = output.get("prediction", "").lower()
    return float(expected.lower() in prediction) if expected else 0.0


def run():
    examples = [
        ("Put one tiny paper-inspired example here.", "expected phrase"),
    ]
    rows = []
    for example, expected in examples:
        base = baseline(example)
        proto = paper_inspired(example)
        rows.append({
            "example": example,
            "baseline_score": score(base, expected),
            "prototype_score": score(proto, expected),
            "prototype_notes": proto,
            "metric": "expected phrase match",
            "failure_condition": "prototype_score <= baseline_score",
        })
    return rows


if __name__ == "__main__":
    for row in run():
        print(row)
`;

export default function LabModal({ span, locale, paperId, paperTitle, sourceText, onClose }: Props) {
  const text = UI_TEXT[locale].lab;
  const summary = labSummary(span, locale);
  const [backendCard, setBackendCard] = useState("");
  const [starterCode, setStarterCode] = useState(STARTER_CODE);
  const [growthIdeas, setGrowthIdeas] = useState<string[]>([]);
  const [growthStatus, setGrowthStatus] = useState(
    locale === "ko" ? "다음 실험 아이디어 대기 중..." : "Waiting for next ideas...",
  );
  const [backendStatus, setBackendStatus] = useState(
    locale === "ko" ? "백엔드 실험 카드 생성 중..." : "Generating backend experiment card...",
  );
  const [starterRunStatus, setStarterRunStatus] = useState("");
  const [starterRows, setStarterRows] = useState<Array<Record<string, unknown>>>([]);
  const [isRunningStarter, setIsRunningStarter] = useState(false);
  const [miniLabStatus, setMiniLabStatus] = useState("");
  const [miniLabResult, setMiniLabResult] = useState<MiniLabRunResult | null>(null);
  const [isRunningMiniLab, setIsRunningMiniLab] = useState(false);
  const [copyStatus, setCopyStatus] = useState(text.copy);

  useEffect(() => {
    let cancelled = false;
    setBackendStatus(locale === "ko" ? "백엔드 실험 카드 생성 중..." : "Generating backend experiment card...");
    setStarterRunStatus("");
    setStarterRows([]);
    setMiniLabStatus("");
    setMiniLabResult(null);
    setCopyStatus(text.copy);
    setGrowthIdeas([]);
    setGrowthStatus(locale === "ko" ? "다음 실험 아이디어 대기 중..." : "Waiting for next ideas...");
    buildExperiment({ span, paperTitle, sourceText, locale })
      .then(async (result) => {
        if (cancelled) return;
        setBackendCard(result.card);
        setStarterCode(result.starter);
        setBackendStatus(locale === "ko" ? "Python backend 생성 완료" : "Generated by Python backend");
        setGrowthStatus(locale === "ko" ? "Research Growth 아이디어 생성 중..." : "Generating Research Growth ideas...");
        try {
          const growth = await buildGrowthIdeas({
            paperId,
            span,
            paperTitle,
            paperMemory: [
              {
                id: span.id,
                summary: span.original,
                translation: span.translated,
              },
            ],
            miniLabResult: result.card,
            locale,
          });
          if (cancelled) return;
          setGrowthIdeas(growth.ideas.map((idea) => idea.idea));
          if (growth.error || growth.ideas.length === 0) {
            setGrowthStatus(locale === "ko" ? "Growth fallback 확인 필요" : "Growth fallback needs review");
          } else {
            const memorySuffix =
              typeof growth.memoryCount === "number" ? ` · memory ${growth.memoryCount}` : "";
            setGrowthStatus(
              growth.usedFallback
                ? `Growth ready (fallback, ${growth.fineTuningSignal})${memorySuffix}`
                : `Growth ready (${growth.fineTuningSignal})${memorySuffix}`,
            );
          }
        } catch {
          if (cancelled) return;
          setGrowthStatus(locale === "ko" ? "Growth 생성 실패" : "Growth unavailable");
        }
      })
      .catch(() => {
        if (cancelled) return;
        setBackendStatus(locale === "ko" ? "오프라인 예시 사용 중" : "Using offline example");
      });
    return () => {
      cancelled = true;
    };
  }, [span, paperTitle, sourceText, locale, text.copy]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(starterCode);
      setCopyStatus(text.copied);
      window.setTimeout(() => setCopyStatus(text.copy), 1600);
    } catch {
      setCopyStatus(text.copy);
    }
  }

  function handleDownload() {
    const blob = new Blob([starterCode], { type: "text/x-python;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = "starter.py";
    anchor.click();
    URL.revokeObjectURL(url);
  }

  async function handleRunStarter() {
    setIsRunningStarter(true);
    setStarterRunStatus(text.runningSmoke);
    setStarterRows([]);
    try {
      const result = await runStarterCode(starterCode);
      setStarterRows(result.rows);
      setStarterRunStatus(
        result.passed
          ? `${text.smokePassed} · ${result.rows.length} rows`
          : `${text.smokeFailed}: ${result.reasons.join("; ")}`,
      );
    } catch (error) {
      setStarterRunStatus(
        `${text.smokeFailed}: ${error instanceof Error ? error.message : "backend unavailable"}`,
      );
    } finally {
      setIsRunningStarter(false);
    }
  }

  async function handleRunMiniLab() {
    setIsRunningMiniLab(true);
    setMiniLabStatus(text.runningMiniLab);
    setMiniLabResult(null);
    try {
      const result = await runMiniLab({
        code: starterCode,
        paperId,
        paperTitle,
        span,
      });
      setMiniLabResult(result);
      setMiniLabStatus(
        result.passed
          ? `${text.miniLabPassed} · ${result.provider} · ${result.rows.length} rows`
          : `${text.miniLabFailed}: ${result.reasons.join("; ")}`,
      );
    } catch (error) {
      setMiniLabStatus(
        `${text.miniLabFailed}: ${error instanceof Error ? error.message : "backend unavailable"}`,
      );
    } finally {
      setIsRunningMiniLab(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="animate-slide-up flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-border bg-surface shadow-xl">
        {/* Header */}
        <div className="flex shrink-0 items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-2">
            <div className="rounded-lg bg-primary-100 p-1.5">
              <svg
                className="text-primary-700"
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h2 className="text-base font-semibold">Lab Mode</h2>
              <p className="text-xs text-text-muted">
                {text.subtitle}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-text-muted transition-colors hover:bg-surface-hover hover:text-text-primary"
          >
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {/* Selected Span */}
          <div className="mb-5 rounded-xl border border-border bg-surface-secondary p-4">
            <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-text-muted">
              {text.selectedSource}
            </p>
            <p className="mb-2 text-sm text-text-primary">{span.original}</p>
            <p className="text-sm text-text-secondary">{span.translated}</p>
          </div>

          {/* Experiment Spec */}
          <div className="mb-5 grid grid-cols-1 gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-primary-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.paperSays}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {summary.paperSays}
              </p>
            </div>

            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-blue-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.interpretation}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {summary.interpretation}
              </p>
            </div>

            <div className="rounded-xl border border-border p-4">
              <div className="mb-2 flex items-center gap-1.5">
                <div className="h-2 w-2 rounded-full bg-orange-500" />
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">
                  {text.unsupportedAssumption}
                </p>
              </div>
              <p className="text-sm text-text-primary">
                {summary.unsupportedAssumption}
              </p>
            </div>
          </div>

          {/* Experiment Design */}
          <div className="mb-5 rounded-xl border border-primary-200 bg-primary-50/50 p-4">
            <p className="mb-3 flex items-center justify-between text-xs font-semibold text-primary-700">
              <span>ExperimentSpec</span>
              <span className="rounded-full bg-surface px-2 py-0.5 text-[10px] text-text-secondary">
                {backendStatus}
              </span>
            </p>
            {backendCard ? (
              <pre className="max-h-64 whitespace-pre-wrap rounded-lg bg-surface p-3 text-xs leading-relaxed text-text-primary">
                {backendCard}
              </pre>
            ) : (
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.hypothesis}
                  </p>
                  <p className="text-text-primary">
                    The selected mechanism can improve a small measurable
                    behavior over a direct baseline.
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.baseline}
                  </p>
                  <p className="text-text-primary">
                    The simplest version of the task without the selected
                    paper mechanism.
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.metric}
                  </p>
                  <p className="text-text-primary">
                    A task-specific score plus a short failure inspection.
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.failureCondition}
                  </p>
                  <p className="text-text-primary">
                    The paper-inspired variant does not beat the baseline on
                    the chosen score.
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.ablation}
                  </p>
                  <p className="text-text-primary">
                    Remove the selected mechanism and keep every other input
                    fixed.
                  </p>
                </div>
                <div>
                  <p className="text-[10px] font-semibold text-text-muted">
                    {text.toyDataset}
                  </p>
                  <p className="text-text-primary">
                    10-20 hand-built examples derived from the selected paper
                    context.
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Research Growth */}
          <div className="mb-5 rounded-xl border border-border bg-surface p-4">
            <p className="mb-3 flex items-center justify-between text-xs font-semibold text-text-primary">
              <span>Research Growth</span>
              <span className="rounded-full bg-surface-secondary px-2 py-0.5 text-[10px] text-text-secondary">
                {growthStatus}
              </span>
            </p>
            {growthIdeas.length > 0 ? (
              <ul className="space-y-2 text-sm text-text-primary">
                {growthIdeas.map((idea, index) => (
                  <li key={`${idea}-${index}`} className="rounded-lg bg-surface-secondary p-3">
                    {idea}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-text-muted">
                {locale === "ko"
                  ? "실험 카드와 선택한 원문을 바탕으로 다음에 테스트할 아이디어를 준비합니다."
                  : "PaperLens will use the selected span and mini-lab result to suggest the next testable ideas."}
              </p>
            )}
          </div>

          {/* Starter Code */}
          <div className="rounded-xl border border-border">
            <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-text-primary">
                  starter.py
                </span>
                <span className="rounded bg-yellow-100 px-1.5 py-0.5 text-[10px] font-medium text-yellow-700">
                  {text.todos}
                </span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] font-medium text-green-700">
                  {text.smokeTestIncluded}
                </span>
                <button
                  onClick={handleRunStarter}
                  disabled={isRunningStarter}
                  className="rounded-md border border-border px-2.5 py-1 text-[11px] font-medium text-text-secondary hover:bg-surface-hover disabled:opacity-60"
                >
                  {isRunningStarter ? text.runningSmoke : text.runSmoke}
                </button>
                <button
                  onClick={handleRunMiniLab}
                  disabled={isRunningMiniLab}
                  className="rounded-md border border-primary-200 bg-primary-50 px-2.5 py-1 text-[11px] font-semibold text-primary-700 hover:bg-primary-100 disabled:opacity-60"
                >
                  {isRunningMiniLab ? text.runningMiniLab : text.runMiniLab}
                </button>
                <button
                  onClick={handleCopy}
                  className="rounded-md border border-border px-2.5 py-1 text-[11px] font-medium text-text-secondary hover:bg-surface-hover"
                >
                  {copyStatus}
                </button>
              </div>
            </div>
            <pre className="max-h-64 overflow-auto bg-slate-950 p-4 text-xs leading-relaxed text-slate-200">
              <code>{starterCode}</code>
            </pre>
            {starterRunStatus && (
              <div className="border-t border-border bg-surface-secondary px-4 py-3">
                <p className="text-xs font-semibold text-text-primary">{starterRunStatus}</p>
                {starterRows.length > 0 && (
                  <pre className="mt-2 max-h-36 overflow-auto rounded-lg bg-surface p-3 text-[11px] leading-relaxed text-text-secondary">
                    {JSON.stringify(starterRows.slice(0, 3), null, 2)}
                  </pre>
                )}
              </div>
            )}
            {miniLabStatus && (
              <div className="border-t border-border bg-surface-secondary px-4 py-3">
                <p className="text-xs font-semibold text-text-primary">{miniLabStatus}</p>
                {miniLabResult && (
                  <div className="mt-2 space-y-2">
                    <div className="grid grid-cols-1 gap-2 text-[11px] text-text-secondary sm:grid-cols-3">
                      <p className="rounded bg-surface px-2 py-1">
                        provider <span className="font-mono">{miniLabResult.provider}</span>
                      </p>
                      <p className="rounded bg-surface px-2 py-1">
                        source <span className="font-mono">{miniLabResult.sourceHash}</span>
                      </p>
                      <p className="rounded bg-surface px-2 py-1">
                        code <span className="font-mono">{miniLabResult.codeHash}</span>
                      </p>
                    </div>
                    {miniLabResult.logs.length > 0 && (
                      <pre className="max-h-24 overflow-auto rounded-lg bg-surface p-3 text-[11px] leading-relaxed text-text-secondary">
                        {miniLabResult.logs.slice(-6).join("\n")}
                      </pre>
                    )}
                    {miniLabResult.rows.length > 0 && (
                      <pre className="max-h-36 overflow-auto rounded-lg bg-surface p-3 text-[11px] leading-relaxed text-text-secondary">
                        {JSON.stringify(miniLabResult.rows.slice(0, 3), null, 2)}
                      </pre>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex shrink-0 items-center justify-between border-t border-border px-6 py-3">
          <p className="text-[11px] text-text-muted">
            {text.reviewWarning}
          </p>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="rounded-lg border border-border px-4 py-2 text-xs font-medium text-text-secondary hover:bg-surface-hover"
            >
              {text.close}
            </button>
            <button
              onClick={handleDownload}
              className="rounded-lg bg-primary-600 px-4 py-2 text-xs font-semibold text-white hover:bg-primary-700"
            >
              {text.download}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function labSummary(span: Span, locale: Locale) {
  if (locale === "ko") {
    return {
      paperSays: span.original,
      interpretation:
        "이 선택 문장은 mini-lab의 경계가 됩니다. 실험은 이 문장이 직접 말한 구조나 메커니즘만 작게 테스트해야 합니다.",
      unsupportedAssumption:
        "이 문장만으로는 전체 논문 재현, 성능 수치, 데이터셋 적합성까지 증명되지 않습니다.",
    };
  }
  return {
    paperSays: span.original,
    interpretation:
      "Use this selected source line as the mini-lab boundary: test the smallest mechanism it names, not the full paper.",
    unsupportedAssumption:
      "This span alone does not prove full-paper reproduction, expected metrics, or dataset fit.",
  };
}
